config/routes.rb
Rails.application.routes.draw do
  resources :answer_keywords
  resources :questions

  get 'questions/random' => 'questions#show'

  root 'questions#show'

end

app/models/answer_keyword.rb
class AnswerKeyword < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answer_keywords
end

app/controllers/answer_keywords_controller.rb
class AnswerKeywordsController < ApplicationController
  before_action :set_answer_keyword, only: [:show, :edit, :update, :destroy]

  # GET /answer_keywords
  # GET /answer_keywords.json
  def index
    @answer_keywords = AnswerKeyword.all
  end

  # GET /answer_keywords/1
  # GET /answer_keywords/1.json
  def show
  end

  # GET /answer_keywords/new
  def new
    @answer_keyword = AnswerKeyword.new
  end

  # GET /answer_keywords/1/edit
  def edit
  end

  # POST /answer_keywords
  # POST /answer_keywords.json
  def create
    @answer_keyword = AnswerKeyword.new(answer_keyword_params)

    respond_to do |format|
      if @answer_keyword.save
        format.html { redirect_to @answer_keyword, notice: 'Answer keyword was successfully created.' }
        format.json { render :show, status: :created, location: @answer_keyword }
      else
        format.html { render :new }
        format.json { render json: @answer_keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answer_keywords/1
  # PATCH/PUT /answer_keywords/1.json
  def update
    respond_to do |format|
      if @answer_keyword.update(answer_keyword_params)
        format.html { redirect_to @answer_keyword, notice: 'Answer keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer_keyword }
      else
        format.html { render :edit }
        format.json { render json: @answer_keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_keywords/1
  # DELETE /answer_keywords/1.json
  def destroy
    @answer_keyword.destroy
    respond_to do |format|
      format.html { redirect_to answer_keywords_url, notice: 'Answer keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_keyword
      @answer_keyword = AnswerKeyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_keyword_params
      params.require(:answer_keyword).permit(:text, :case_sensitive, :order, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    if ['random', "", nil].include? params[:id]
      params[:id] = rand(1..Question.all.length)
    end
    @question = Question.find(params[:id])
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:prompt, :answer)
    end
end

app/helpers/answer_keywords_helper.rb
module AnswerKeywordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answer_keywords/_form.html.erb
<%= form_for(@answer_keyword) do |f| %>
  <% if @answer_keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer_keyword.errors.count, "error") %> prohibited this answer_keyword from being saved:</h2>

      <ul>
      <% @answer_keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :case_sensitive %><br>
    <%= f.check_box :case_sensitive %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.text_field :question_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answer_keywords/edit.html.erb
<h1>Editing Answer Keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer_keyword %> |
<%= link_to 'Back', answer_keywords_path %>

app/views/answer_keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answer Keywords</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Case sensitive</th>
      <th>Order</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answer_keywords.each do |answer_keyword| %>
      <tr>
        <td><%= answer_keyword.text %></td>
        <td><%= answer_keyword.case_sensitive %></td>
        <td><%= answer_keyword.order %></td>
        <td><%= answer_keyword.question.id %></td>
        <td><%= link_to 'Show', answer_keyword %></td>
        <td><%= link_to 'Edit', edit_answer_keyword_path(answer_keyword) %></td>
        <td><%= link_to 'Destroy', answer_keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer keyword', new_answer_keyword_path %>

app/views/answer_keywords/new.html.erb
<h1>New Answer Keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', answer_keywords_path %>

app/views/answer_keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @answer_keyword.text %>
</p>

<p>
  <strong>Case sensitive:</strong>
  <%= @answer_keyword.case_sensitive %>
</p>

<p>
  <strong>Order:</strong>
  <%= @answer_keyword.order %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer_keyword.question %>
</p>

<%= link_to 'Edit', edit_answer_keyword_path(@answer_keyword) %> |
<%= link_to 'Back', answer_keywords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prompt %><br>
    <%= f.text_field :prompt %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Prompt</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.prompt %></td>
        <td><%= question.answer %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<table class="question">
  <tr><td>
  <div>
  	<div class="prompt">
  			<br /><br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <%= @question.prompt %>
      <div class='status' hidden='hidden'>
        
      </div>
      <div class='answer' hidden='hidden'>
        <br /><br /><br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= @question.answer %>
      </div>
      <% AnswerKeyword.where(question: @question.id).each do |keyword| %>
        <div class='answerkeyword' hidden='hidden'><%= keyword.text %></div>
      <% end %>
    </div>

  	<%= image_tag "card" + rand(1..6).to_s + ".jpg", alt: @question.prompt, class: "question" %>
	</div>
	</td>
  </tr>
  <tr>
    <td>
      <h4>Your answer:</h4>
      <input type='text' name='answer' id='answerbox' size='40' /><br />
      <button name='submit' id='submitbutton'>Submit!</button><br />
      <% rand_q = Question.all.shuffle.first %>
      <%= link_to "Next Question", rand_q, class: "largelink" %>
    </td>
  </tr>
</table>
<p>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>
</p>